on:
  push:
    branches:
      - master
    paths:
      - governance/polls/**
      - '!governance/polls/meta/polls.json'
  workflow_dispatch:
jobs:
  aggregate_polls:
    runs-on: ubuntu-latest
    name: Aggregates all of the polls into a single file, creating a pull request with the new file.
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Upload
        id: upload
        uses: lasthyphen/action-flows@v1.1.2
        with:
          network: 'dijets'
          tags-file: 'governance/polls/meta/poll-tags.json'
          output-file: 'governance/polls/meta/polls.json'
      - name: Update pull request with polls changes 
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: 'Added polls aggregated file'
          add: 'governance/polls/meta/polls.json'
          fetch: false
          push: false
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
